### ISSUE TITLE
Error in logistic regression.

### ISSUE THREAD

**Issue by TushtiSavarn** [TushtiSavarn/AI-projects#1]
There are some errors in logistic regression file . Kindly resolve them

**Comment by radharashmitha** [comment]
Hi @TushtiSavarn ! I'm here to fix this issue.
Will you assign this issue to me to work on it.

**Comment by TushtiSavarn** [comment]
@radharashmitha  I have assigned . Thank you for helping

**Comment by TushtiSavarn** [comment]
@radharashmitha you need to create pull request so that error can be fixed and your solution will be merged in this repo

**Comment by radharashmitha** [comment]
I already created a pull request tushti.

**Comment by radharashmitha** [comment]
[image: image.png]
